name: PayDay
main: tzer0.PayDay.PayDay
version: 0.3
author: TZer0
commands:
    pd:
        description: Administrates payment-settings
        usage: /pd
    payday:
        description: Administrates payment-settings
        usage: /payday
